spring.application.name=norte-api

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,
  org.springframework.boot.autoconfigure.hibernate.autoconfigure.HibernateJpaAutoConfiguration,
  org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration