spring.application.name=norte-api

spring.datasource.url=jdbc:postgresql://localhost:5432/norte
spring.datasource.username=norte
spring.datasource.password=norte

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true